version: '3.8'

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: fitness-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fitness_db
      MYSQL_USER: fitness_user
      MYSQL_PASSWORD: fitness_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: fitness-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Spring Boot 애플리케이션
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitness-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      DATABASE_URL: jdbc:mysql://mysql:3306/fitness_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      DATABASE_USERNAME: fitness_user
      DATABASE_PASSWORD: fitness_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: local-jwt-secret-key-for-development-only-32-chars-minimum
    depends_on:
      - mysql
      - redis
    volumes:
      - app_logs:/var/log/fitness

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local

networks:
  default:
    name: fitness-network