# 테스트 환경 설정 (H2 메모리 DB 전용)
spring:
  # 데이터베이스 설정 - H2 메모리 DB
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  # SQL 초기화 비활성화 (JPA 엔티티로 스키마 생성)
  sql:
    init:
      mode: never
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false # 테스트 시 로그 줄이기
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
      
  # DevTools 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      
# JWT 설정 (테스트용)
jwt:
  secret: test-jwt-secret-key-for-development-only-32-chars-minimum
  expiration: 86400000 # 24시간

# 로깅 설정
logging:
  level:
    com.fitness: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG