# 프로덕션 환경 설정
spring:
  # 데이터베이스 설정
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate # 프로덕션에서는 스키마 검증만
    show-sql: false
    
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      
# JWT 설정 (프로덕션용)
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24시간

# 로깅 설정
logging:
  level:
    root: INFO
    com.fitness: INFO
  file:
    name: /var/log/fitness/application.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# 서버 설정
server:
  port: ${SERVER_PORT:8080}