# 로컬 개발 환경 설정 (로컬 MySQL 서버 사용)
spring:
  # 데이터베이스 설정 - 로컬 MySQL 서버
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root
    password: 1234
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop # 로컬에서만 자동 스키마 생성
    show-sql: true
    
  # DevTools 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      
# JWT 설정 (로컬용)
jwt:
  secret: local-jwt-secret-key-for-development-only-32-chars-minimum
  expiration: 86400000 # 24시간

# 로깅 설정
logging:
  level:
    com.fitness: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG